// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: proto/minion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMinion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateMinion) Reset() {
	*x = CreateMinion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_minion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMinion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMinion) ProtoMessage() {}

func (x *CreateMinion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMinion.ProtoReflect.Descriptor instead.
func (*CreateMinion) Descriptor() ([]byte, []int) {
	return file_proto_minion_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMinion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MinionCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authenticated  bool   `protobuf:"varint,1,opt,name=authenticated,proto3" json:"authenticated,omitempty"`
	MinionId       int64  `protobuf:"varint,2,opt,name=minionId,proto3" json:"minionId,omitempty"`
	Registeredname string `protobuf:"bytes,3,opt,name=registeredname,proto3" json:"registeredname,omitempty"`
}

func (x *MinionCreateResponse) Reset() {
	*x = MinionCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_minion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionCreateResponse) ProtoMessage() {}

func (x *MinionCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionCreateResponse.ProtoReflect.Descriptor instead.
func (*MinionCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_minion_proto_rawDescGZIP(), []int{1}
}

func (x *MinionCreateResponse) GetAuthenticated() bool {
	if x != nil {
		return x.Authenticated
	}
	return false
}

func (x *MinionCreateResponse) GetMinionId() int64 {
	if x != nil {
		return x.MinionId
	}
	return 0
}

func (x *MinionCreateResponse) GetRegisteredname() string {
	if x != nil {
		return x.Registeredname
	}
	return ""
}

type CommandToMinion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time             string `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`                         // Time time as a string
	Scheduletask     bool   `protobuf:"varint,2,opt,name=scheduletask,proto3" json:"scheduletask,omitempty"`        // Don't wait to execute it now
	Timeout          int64  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`                  // to be used later
	Commandtype      string `protobuf:"bytes,4,opt,name=commandtype,proto3" json:"commandtype,omitempty"`           // the command type (based on structs)
	Marshaledcommand string `protobuf:"bytes,5,opt,name=marshaledcommand,proto3" json:"marshaledcommand,omitempty"` // The marshaled struct
}

func (x *CommandToMinion) Reset() {
	*x = CommandToMinion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_minion_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandToMinion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandToMinion) ProtoMessage() {}

func (x *CommandToMinion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minion_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandToMinion.ProtoReflect.Descriptor instead.
func (*CommandToMinion) Descriptor() ([]byte, []int) {
	return file_proto_minion_proto_rawDescGZIP(), []int{2}
}

func (x *CommandToMinion) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *CommandToMinion) GetScheduletask() bool {
	if x != nil {
		return x.Scheduletask
	}
	return false
}

func (x *CommandToMinion) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *CommandToMinion) GetCommandtype() string {
	if x != nil {
		return x.Commandtype
	}
	return ""
}

func (x *CommandToMinion) GetMarshaledcommand() string {
	if x != nil {
		return x.Marshaledcommand
	}
	return ""
}

type CommandFromMinion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Readytoreceive bool   `protobuf:"varint,1,opt,name=readytoreceive,proto3" json:"readytoreceive,omitempty"` // True == client will accept a new command
	Result         string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                  // The stdout/stderr output from the client
	Success        bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`               // Was the command successful
}

func (x *CommandFromMinion) Reset() {
	*x = CommandFromMinion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_minion_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandFromMinion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandFromMinion) ProtoMessage() {}

func (x *CommandFromMinion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minion_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandFromMinion.ProtoReflect.Descriptor instead.
func (*CommandFromMinion) Descriptor() ([]byte, []int) {
	return file_proto_minion_proto_rawDescGZIP(), []int{3}
}

func (x *CommandFromMinion) GetReadytoreceive() bool {
	if x != nil {
		return x.Readytoreceive
	}
	return false
}

func (x *CommandFromMinion) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandFromMinion) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CmdRunSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Minions string `protobuf:"bytes,1,opt,name=minions,proto3" json:"minions,omitempty"` // space separated list of minions
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *CmdRunSend) Reset() {
	*x = CmdRunSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_minion_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdRunSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRunSend) ProtoMessage() {}

func (x *CmdRunSend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minion_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRunSend.ProtoReflect.Descriptor instead.
func (*CmdRunSend) Descriptor() ([]byte, []int) {
	return file_proto_minion_proto_rawDescGZIP(), []int{4}
}

func (x *CmdRunSend) GetMinions() string {
	if x != nil {
		return x.Minions
	}
	return ""
}

func (x *CmdRunSend) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CmdRunResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinionCmdResult []*MinionCmdRunResult `protobuf:"bytes,1,rep,name=minionCmdResult,proto3" json:"minionCmdResult,omitempty"` //
}

func (x *CmdRunResult) Reset() {
	*x = CmdRunResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_minion_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CmdRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRunResult) ProtoMessage() {}

func (x *CmdRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minion_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRunResult.ProtoReflect.Descriptor instead.
func (*CmdRunResult) Descriptor() ([]byte, []int) {
	return file_proto_minion_proto_rawDescGZIP(), []int{5}
}

func (x *CmdRunResult) GetMinionCmdResult() []*MinionCmdRunResult {
	if x != nil {
		return x.MinionCmdResult
	}
	return nil
}

type MinionCmdRunResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True == the command was successful, False == the command failed
	Result  string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`    // The stdout/stderr output from the minion that ran the command
}

func (x *MinionCmdRunResult) Reset() {
	*x = MinionCmdRunResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_minion_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinionCmdRunResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinionCmdRunResult) ProtoMessage() {}

func (x *MinionCmdRunResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minion_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinionCmdRunResult.ProtoReflect.Descriptor instead.
func (*MinionCmdRunResult) Descriptor() ([]byte, []int) {
	return file_proto_minion_proto_rawDescGZIP(), []int{6}
}

func (x *MinionCmdRunResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MinionCmdRunResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_minion_proto protoreflect.FileDescriptor

var file_proto_minion_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x0c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x80, 0x01, 0x0a, 0x14, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54,
	0x6f, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x74, 0x61, 0x73, 0x6b, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6d,
	0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x65, 0x64, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x65, 0x64,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x6d, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x74, 0x6f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x72, 0x65, 0x61, 0x64, 0x79, 0x74, 0x6f, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x40, 0x0a, 0x0a, 0x43, 0x6d, 0x64, 0x52, 0x75, 0x6e,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x54, 0x0a, 0x0c, 0x43, 0x6d, 0x64, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x44, 0x0a, 0x0f, 0x6d, 0x69, 0x6e, 0x69,
	0x6f, 0x6e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f,
	0x6e, 0x43, 0x6d, 0x64, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0f, 0x6d,
	0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x43, 0x6d, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x46,
	0x0a, 0x12, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x43, 0x6d, 0x64, 0x52, 0x75, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xd9, 0x01, 0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x77, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x12, 0x19, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x1a, 0x17, 0x2e,
	0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x6f,
	0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x34, 0x0a, 0x06,
	0x43, 0x6d, 0x64, 0x52, 0x75, 0x6e, 0x12, 0x12, 0x2e, 0x6d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e,
	0x43, 0x6d, 0x64, 0x52, 0x75, 0x6e, 0x53, 0x65, 0x6e, 0x64, 0x1a, 0x14, 0x2e, 0x6d, 0x69, 0x6e,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6d, 0x64, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x62, 0x72, 0x75, 0x75, 0x6e, 0x2f, 0x62, 0x62, 0x72, 0x75, 0x75, 0x6e, 0x2f, 0x67,
	0x61, 0x6c, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_minion_proto_rawDescOnce sync.Once
	file_proto_minion_proto_rawDescData = file_proto_minion_proto_rawDesc
)

func file_proto_minion_proto_rawDescGZIP() []byte {
	file_proto_minion_proto_rawDescOnce.Do(func() {
		file_proto_minion_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_minion_proto_rawDescData)
	})
	return file_proto_minion_proto_rawDescData
}

var file_proto_minion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_minion_proto_goTypes = []interface{}{
	(*CreateMinion)(nil),         // 0: minion.CreateMinion
	(*MinionCreateResponse)(nil), // 1: minion.MinionCreateResponse
	(*CommandToMinion)(nil),      // 2: minion.CommandToMinion
	(*CommandFromMinion)(nil),    // 3: minion.CommandFromMinion
	(*CmdRunSend)(nil),           // 4: minion.CmdRunSend
	(*CmdRunResult)(nil),         // 5: minion.CmdRunResult
	(*MinionCmdRunResult)(nil),   // 6: minion.MinionCmdRunResult
}
var file_proto_minion_proto_depIdxs = []int32{
	6, // 0: minion.CmdRunResult.minionCmdResult:type_name -> minion.MinionCmdRunResult
	0, // 1: minion.MinionService.RegisterNewMinion:input_type -> minion.CreateMinion
	3, // 2: minion.MinionService.GetCommands:input_type -> minion.CommandFromMinion
	4, // 3: minion.MinionService.CmdRun:input_type -> minion.CmdRunSend
	1, // 4: minion.MinionService.RegisterNewMinion:output_type -> minion.MinionCreateResponse
	2, // 5: minion.MinionService.GetCommands:output_type -> minion.CommandToMinion
	5, // 6: minion.MinionService.CmdRun:output_type -> minion.CmdRunResult
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_minion_proto_init() }
func file_proto_minion_proto_init() {
	if File_proto_minion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_minion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMinion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_minion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_minion_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandToMinion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_minion_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandFromMinion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_minion_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdRunSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_minion_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CmdRunResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_minion_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinionCmdRunResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_minion_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_minion_proto_goTypes,
		DependencyIndexes: file_proto_minion_proto_depIdxs,
		MessageInfos:      file_proto_minion_proto_msgTypes,
	}.Build()
	File_proto_minion_proto = out.File
	file_proto_minion_proto_rawDesc = nil
	file_proto_minion_proto_goTypes = nil
	file_proto_minion_proto_depIdxs = nil
}
